//export const ADD_CATEGORY_ES6 = "ADD_CATEGORY_ES6";
export const ADD_CATEGORY = "ADD_CATEGORY";
//export const ADD_CATEGORY_REACT = "ADD_CATEGORY_REACT";
export const ADD_SUBCATEGORY = "ADD_SUBCATEGORY";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
